on: push

jobs:
  test:
    name: lint
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [^10, ^12, ^14, ^15]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: install
        run: yarn install

      - name: lint
        run: yarn lint
