on: push

jobs:
  test:
    name: lint
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node: [^10, ^12, ^14, ^16]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: install (node 10)
        if: matrix.node == '^10'
        run: yarn install --ignore-engines

      - name: install
        if: matrix.node != '^10'
        run: yarn install

      - name: lint
        run: yarn lint
