on: push

jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node: [^10, ^12, ^14, ^15]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: node
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node }}

      - name: install
        run: yarn install

      - name: test
        run: yarn test

      - name: test-cjs
        run: yarn test-cjs
