on: push

jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [^6, ^8, ^10, ^12, ^14]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: install
        run: yarn install --ignore-engines

      - name: test
        run: yarn test

      - name: test-cjs
        run: yarn test-cjs
